config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  # resources :posts, except:[:destroy] do
  #   #resources :comments, only:[:create]
  # end
  
  resources :posts, except:[:destroy]  do
    member do
      post 'vote'
    end
    resources :comments, only:[:create]
  end

  resources :comments, only:[:show]  do
    member do
      post 'vote'
    end
  end

  # resources :posts, except:[:destroy]  do
  #     member do
  #     post :votes, only:[:create]
  #   end
  # end

  resources :categories, only:[:new, :create, :show]
  resources :users, except:[:index, :destroy]
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

end 
#   get '/register', to: "users#new" 
#   post '/register', to: "users#create" 
#   get '/profile', to: "users#show" 
#   get '/edit_profile', to: "users#edit" 
#   patch '/profile', to: "users#update"

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  has_many :votes, as: :voteable
  validates :body, presence: true
  
  def total_votes
    self.vote_up - self.vote_down
  end

  def vote_up
    self.votes.where(vote: true).size
  end
  
  def vote_down
    self.votes.where(vote: false).size
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable
  
  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 10}
  validates :url, presence: true

  def total_votes
    self.vote_up - self.vote_down
  end

  def vote_up
    self.votes.where(vote: true).size
  end
  
  def vote_down
    self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post 
  belongs_to :category 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false
  validates :username, uniqueness: true
  validates :password, on: :create, length: {minimum:5} 
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true 
  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :require_user
  

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "You need to log in"
      redirect_to posts_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end
    
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Your category was saved"
      redirect_to root_path
    else
      render "new"
    end
  end
   
  def show
    @category = Category.find(params[:id])
  end

  private
  
  def category_params # SO YOU CAN USE THE FIELD ON THE FORMS
    params.require(:category).permit(:name)
  end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @post = Post.find(params[:post_id])

    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user
    if @comment.save
      flash[:notice] = "Your comment was saved"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def show
  end

  def vote
    @comment = Comment.find(params[:id])
    @post = @comment.post(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    if @vote.valid?
      flash[:notice]= "You voted"
      redirect_to post_path(@post)
    else
      flash[:error]= "Didn't work"
      redirect_to :back
    end
  end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only:[:edit, :update]
  
  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
    
  end
  
  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save(post_params)
      flash[:notice] = "Your post was saved"
      redirect_to posts_path
    else
      render "new"
    end
  end
  
  def edit
  end
  
  def update
       
    if @post.update(post_params)
      flash[:notice] = "Your post was updated"
      redirect_to post_path
    else
      render "edit"
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
      if @vote.valid?
        flash[:error] = "You voted!"
        redirect_to :back
      else
        flash[:notice] = "Something went wrong!"
        redirect_to root_path
      end
  end


  private

  def post_params # SO YOU CAN USE THE FIELD ON THE FORMS
    params.require(:post).permit(:url, :name, :body, :comment, :category, :creator, :username, :title, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def require_same_user
    @user = User.find(params[:id])
    if current_user != @user
      flash[:error] = "you cannot do that!"
      redirect_to posts_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Hello"
      redirect_to posts_path
    else
      flash[:notice]= "There's something wrong"
      redirect_to posts_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are logged out"
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Postit!"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show

  end

  def edit
    
  end
  
  def update
    if @user.update(params.require(:user).permit(:username, :email, :password))
      flash[:notice] = "Your profile was updated"
      redirect_to posts_path
    else
      render "edit"
    end
  end

private
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "you cannot do that!"
      redirect_to posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end

end

app/views/categories/_category.html.erb
<span class='badge'> <%= link_to category.name %></span> 

app/views/categories/new.html.erb
<% if logged_in? %>
  <%= render 'shared/error', obj: @category %>
  <%= render 'shared/content_title', title: "New category" %>

  <div class='well'>
    <%= form_for @category do |f| %>
      <div class='control-group'> 
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <br>
      <%= f.submit 'Create category', class: 'btn-btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + "&raquo; #{@category.name}" .html_safe %>
<%= render 'shared/content_title', title: header  %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% if comment.valid? %>
  <div class='row'>
    <div class='span0 well text-center'> 
      <%= link_to vote_comment_path(comment, vote: true), method: 'post' do %>
        <i class='icon-arrow-up'></i>
      <% end %>
        <br/>
      <%= pluralize(comment.total_votes, 'vote') %> 
        <br/>
      <%= link_to vote_comment_path(comment, vote: false), method: 'post' do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    </div>


    <div class='span8 well'> 
      <em>"<%= comment.body %>"</em>
      
          on <%= link_to comment.post.title, post_path(comment.post) %>
       
       <br>
      <span class='quiet'> by </span> <%= link_to comment.creator.username, user_path(comment.creator) %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<% if logged_in? %>
  <div class='nav_item'>
    <%= link_to 'new post', new_post_path, class: 'btn btn-success btn-small' %>
  </div>
  <div class='nav_item'>
    <%= link_to 'Log out', logout_path, method: :delete, class: 'btn btn-success btn-small' %>
  </div>
  <div class='btn-group nav_item'>
    <%= link_to 'Category', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %> Category <span   class= 'caret' > </span>
    <% end %>
    <ul class='dropdown-menu'>
      <% Category.all.each do |category| %>
        <li> 
          <%= link_to category.name, category_path(category) %>
        </li>
      <% end %>
      <li class= 'divider'></li>
      <i class="icon-plus"></i>
      <%= link_to "New Category", new_category_path, class: 'btn-btn-small' %>
      </ul>
  </div>
  <div class='btn-group nav_item'>
    <%= link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do %> <%= current_user.username %> <span class= 'caret' > </span>
    <% end %>
    <ul class='dropdown-menu'>
      <li> 
        <%= link_to edit_user_path(@user) do %>
          <i class='icon-pencil'></i>
          edit profile
        <% end %>
      </li>
      <li> 
        <%= link_to user_path(current_user) do %>
          <i class='icon-user'></i>
          view profile
        <% end %> 
      </li>
      <li> 
        <%= link_to logout_path, method: :delete  do %>
          <i class='icon-circle-arrow-left'></i>
          log out
        <% end %>
      </li>
    </ul>
  </div>
<% else %>
  <ul class="nav">
    <li>
      <%= link_to "Sign-up", new_user_path %>
    </li>
    <li>
      <%= link_to "Log-in", login_path %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_commentform.html.erb
  <%= form_for [@post, @comment] do |f| %>
   <%= render 'shared/error', obj: @comment %>
    <%= f.text_area :body %>
     <br>
    <%= f.submit 'Create', class: 'btn-btn-primary' %>
  <% end %>

app/views/posts/_form.html.erb
<%= render 'shared/error', obj: @post %>


<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'> 
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'> 
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'> 
      <%= f.label :description %>
      <%= f.text_area :description, rows: 10 %>
    </div>
    <div class="field">
      <%= hidden_field_tag "post[category_ids][]", nil %>
      <% Category.all.each do |category| %>
        <%= check_box_tag "post[category_ids][]", category.id,
          @post.category_ids.include?(category.id), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name %> 
      <% end %>
    </div>
    <br>
    <%= f.submit(@post.new_record? ? 'Create': 'Update', class: 'btn-btn-primary') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div>
  <% if logged_in? %>
    <div class='span0 well text-center'> 
      <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br/>
      <%= pluralize(post.total_votes, 'vote') %> 
        <br/>
      <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    </div>
  <% end %>
  <div class='row'>
    <div class='span8 well'> 
      <%= render post.categories %> 
      <p> <%= link_to post.title, display_url(post.url) %></p>
      <p> <%= post.description %></p>
      <p><span class='quiet'>
        Submitted by </span><%= link_to post.creator.username, user_path(post.creator) %></P>
      <small> <%= time_ago_in_words(post.created_at) + ' ago'
         %></small>
        <p><small><span><%= link_to("#{post.comments.size} comments", post_path(post))%>
      </span></small></p>
      
    </div>
  </div>
</div>
    

app/views/posts/edit.html.erb
<% if logged_in? %>
  <h4>Edit Post</h4>
  <%= render 'shared/content_title', title: 'Edit this post' %>

  <%= render 'form' %>
<% end %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All post' %>
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>

app/views/posts/new.html.erb
<% if logged_in? %>
  <h4>New Post</h4>
  <%= render 'shared/content_title', title: 'Create a new post' %>

  <%= render 'form' %>
<% end %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class= 'pull-right'>
    <%=link_to 'edit this post', edit_post_path(@post)%>
  </p>
  <%= render 'shared/content_title', title: @post.title %>

  <p>
    <%= @post.description %>
  </p>
    </hr>

   <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/error', obj: @comment %>
    <div class='control-group'>
      <%= f.label :body, "Leave a comment" %>
      <%= f.text_area :body, rows: 3, class: 'span4'%>
    </div>
      <br>
      <%= f.submit 'Create', class: 'btn-btn-primary' %>
    <% end %>

    <% @post.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class= 'row'>
     <div class='alert alert-error span8'>
    <h5><%= pluralize(obj.errors.count, 'error') %> prohibited your category to save</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class='well'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group'>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
      <br>
      <%= f.submit @user.new_record? ? "Register" : "Update Profile", class: 'btn btn-primary' %>
  <%end%>
</div>

app/views/users/_profile_page.html.erb
<div class='well'>
  <dl class='dl-horizonal'>
    <dt>Username: </dt>
      <dd><%= @user.username %></dd>
  </dl>
  <dl class='dl-horizonal'>
    <dt>Email: </dt>
      <dd><%= @user.email %></dd>
  </dl>
</div>
<h5><%= @user.username %>'s Activity</h5> 
  
  <ul class='nav nav-tabs'>
    <li class='<%= 'active' if params[:tab].nil? %>'>
      <%= link_to "posts (#{@user.posts.size})", user_path(@user) %>
    </li>
    <li class='<%= 'active' if params[:tab] =='comments' %>'>
      <%= link_to "comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
    </li>
  </ul>

  <% if params[:tab].nil? %>
    <% @user.posts.each do |post| %>
      <%= render 'posts/post', post: post %>
    <% end %>
  <% elsif params[:tab] =='comments' %>
    <% @user.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment, show_post: true %>
    <% end %>
  <% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this profile' %>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Create your profile' %> 
<%= render '/shared/error', obj: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %> 
<%= render 'profile_page' %> 